version: "3.8"

services:
  nginx:
    build:
      context: ./docker/images
      dockerfile: nginx.Dockerfile
    working_dir: /var/www/html
    container_name: real_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/logs/nginx_log:/var/log/nginx
      - ./docker/config/nginx/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - php 
      - mysql
      - redis  

  php:
    build:
      context: ./docker/images
      dockerfile: php.Dockerfile
    working_dir: /var/www/html
    container_name: real_php
    volumes:
      - .:/var/www/html:cached 
      - ./docker/logs/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  mysql:
    build:
      context: ./docker/images
      dockerfile: mysql.Dockerfile
    container_name: phongvu_mysql
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql:delegated 
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Sử dụng volume để lưu dữ liệu Redis
    command: redis-server --appendonly yes # Bật chế độ lưu trữ lâu dài (AOF)

volumes:
  redis_data: {} # Định nghĩa volume tại mức root
