<div class="">
    <div class="" style="border-top: 3px solid rgb(20, 53, 195);position: relative;">
         <div class="" style="background-color: rgb(255, 255, 255);padding: 1rem 0px;">
               <div class="css-1734w3">
                    <div class="css-10enlo d-flex">
                        <div class="" style="width: 20%">
                            <div class="css-uwn2d9">Hỗ trợ Khách hàng</div>
                            <a href="https://help.phongvu.vn/dich-vu-khach-hang/the-thanh-vien" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Hướng dẫn mua thẻ online</a>
                            <a href="https://help.phongvu.vn/dich-vu-khach-hang/the-thanh-vien" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Ưu đãi dành cho doanh nghiệp</a>
                            <a href="https://help.phongvu.vn/dich-vu-khach-hang/the-thanh-vien" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Chính sách trả góp</a>
                            <a href="https://help.phongvu.vn/dich-vu-khach-hang/the-thanh-vien" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Dịch vụ sữa chữa</a>
                        </div>
                        <div class="css-ae081h"><div class="css-uwn2d9">Chính sách mua hàng</div><a href="https://help.phongvu.vn/chinh-sach-ban-hang/dieu-kien-giao-dich" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Điều kiện giao dịch chung</a><a href="https://help.phongvu.vn/chinh-sach-ban-hang/bao-hanh" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Chính sách bảo hành</a><a href="https://help.phongvu.vn/chinh-sach-ban-hang/doi-tra-va-hoan-tien" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Chính sách đổi trả</a><a href="https://help.phongvu.vn/chinh-sach-ban-hang/chinh-sach-thanh-toan" class="css-1l4xpub">Chính sách thanh toán</a><a href="https://help.phongvu.vn/chinh-sach-ban-hang/giao-hang-va-lap-dat-tai-nha" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Giao hàng và Lắp đặt tại nhà</a><a href="https://help.phongvu.vn/chinh-sach-ban-hang/dich-vu-lap-dat-va-nang-cap-tai-cua-hang" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Dịch vụ lắp đặt và nâng cấp PC/ Laptop tại cửa hàng &amp; TTBH</a><a href="https://help.phongvu.vn/chinh-sach-ban-hang/chinh-sach-bao-mat-thanh-toan" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Chính sách bảo mật thanh toán</a></div>
                        <div class="css-ae081h"><div class="css-uwn2d9">Thông tin Phong Vũ</div><a href="https://help.phongvu.vn/" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Giới thiệu Phong Vũ</a><a href="https://phongvu.vn/p/he-thong-showroom-phong-vu" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Hệ thống cửa hàng</a><a href="https://help.phongvu.vn/dich-vu-khach-hang/trung-tam-bao-hanh" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Trung tâm bảo hành</a><a href="https://help.phongvu.vn/chinh-sach-chung/bao-mat-thong-tin" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Chính sách bảo mật</a><a href="https://phongvu.vn/cong-nghe" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Tin công nghệ</a><a href="https://phongvu.vn/hoi-dap" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Hỏi đáp</a><a href="https://tuyendung.phongvu.vn/" target="_blank" rel="noreferrer noopener" class="css-1l4xpub">Tuyển dụng</a></div>
                        <div class="css-ae081h"><div class="css-uwn2d9">Cộng đồng Phong Vũ</div><div class="css-1icnabn">Gọi mua hàng (miễn phí) <a href="tel:18006867" }="">18006867</a></div><div class="css-1icnabn">Gọi chăm sóc  <a href="tel:18006865" }="">18006865</a></div><a href="https://www.facebook.com/phongvuvietnam/" target="_blank" rel="noreferrer noopener" class="css-1l4xpub"><span size="16" color="#485992" class="css-zmasuu"></span><div class="spacer css-1x3u27e"></div>Facebook Phong Vũ</a><a href="https://www.youtube.com/channel/UCOJ3sqWCc6koR9BScBZkBlA" target="_blank" rel="noreferrer noopener" class="css-1l4xpub"><span size="16" color="#cf2200" class="css-btiuvm"></span><div class="spacer css-1x3u27e"></div>Phong Vũ Media</a><a href="https://www.facebook.com/groups/phongvuvn/" target="_blank" rel="noreferrer noopener" class="css-1l4xpub"><span size="16" color="#00AFF7" class="css-oj6l12"></span><div class="spacer css-1x3u27e"></div>Phong Vũ Hội</a><a href="https://zalo.me/3951230446867820356" target="_blank" rel="noreferrer noopener" class="css-1l4xpub"><span size="16" color="#0573ff" class="css-1vir8ad"></span><div class="spacer css-1x3u27e"></div>OA Phong Vũ (zalo)</a></div>
                        <div class="css-ae081h"><div class="css-uwn2d9">Email liên hệ</div><div class="css-1icnabn">Hỗ trợ Khách hàng:<br> <a href="mailto:cskh@phongvu.vn">cskh@phongvu.vn</a></div><div class="css-1icnabn">Liên hệ báo giá:<br> <a href="mailto:baogia@phongvu.vn">baogia@phongvu.vn</a></div><div class="css-1icnabn">Hợp tác phát triển:<br> <a href="mailto:hoptac@phongvu.vn">hoptac@phongvu.vn</a></div></div>
                    </div>


               </div>
               <div class="css-1734w3"><div class="css-z54kij"><div class="css-42iko7"><div class="css-uwn2d9">Phương thức thanh toán</div><a href="https://help.phongvu.vn/chinh-sach-ban-hang/huong-dan-thanh-toan-vnpay-qr" class="css-1erzqxf"><span size="30" color="#3e3e3e" class="css-1qnwmuv"></span><div class="spacer css-1x3u27e"></div>QR Code</a><a href="https://help.phongvu.vn/chinh-sach-ban-hang/phuong-thuc-thanh-toan#thanh-toan-tien-mat" class="css-1erzqxf"><span size="30" color="#3e3e3e" class="css-1l7prcq"></span><div class="spacer css-1x3u27e"></div>Tiền mặt</a><a href="https://help.phongvu.vn/chinh-sach-ban-hang/phuong-thuc-thanh-toan#thanh-toan-tra-gop" class="css-1erzqxf"><span size="30" color="#3e3e3e" class="css-1vkz9o9"></span><div class="spacer css-1x3u27e"></div>Trả góp</a><a href="https://help.phongvu.vn/chinh-sach-ban-hang/phuong-thuc-thanh-toan#thanh-toan-the-atm-noi-dia-internet-banking" class="css-1erzqxf"><span size="30" color="#3e3e3e" class="css-1p02a2r"></span><div class="spacer css-1x3u27e"></div>Internet Banking</a></div><div class="css-2ig3pg"><div class="css-uwn2d9">Danh sách các ngân hàng thanh toán online</div><img src="https://shopfront-cdn.tekoapis.com/static/vnpay_banks.png" alt="" class="css-1equo6g"></div></div></div>
               {{--  --}}
               <nav class="css-q8uykj"><div class="css-1734w3"><div class="css-2gxw46"><div class="css-wtxc87"><div class="css-j08kxf">Công ty cổ phần thương mại - dịch vụ Phong Vũ</div><div class="css-1qw662x">© 1997 - 2020 Công Ty Cổ Phần Thương Mại - Dịch Vụ Phong Vũ<br>Giấy chứng nhận đăng ký doanh nghiệp: 0304998358 do Sở KH-ĐT TP.HCM cấp lần đầu ngày 30 tháng 05 năm 2007<br>Website phongvu.vn thuộc quyền sở hữu của Công ty Cổ phần Thương Mại - Dịch Vụ Phong Vũ và được phát triển bởi Teko.</div></div><div class="css-wtxc87"><div><span class="css-1hopt4r">Địa chỉ trụ sở chính</span>:<div class="css-1qw662x">Tầng 5, Số 117-119-121 Nguyễn Du, Phường Bến Thành, Quận 1, Thành Phố Hồ Chí Minh</div></div><div><span class="css-1hopt4r">Văn phòng điều hành miền Bắc</span>:<div class="css-1qw662x">Tầng 2, Số 47 Phố Thái Hà, Phường Trung Liệt, Quận Đống Đa, Thành phố Hà Nội</div></div><div><span class="css-1hopt4r">Văn phòng điều hành miền Nam</span>:<div class="css-1qw662x">677/2A Điện Biên Phủ, Phường 25 , Quận Bình Thạnh , TP. Hồ Chí Minh</div></div></div><div class="css-nt4onc"><a href="http://online.gov.vn/Home/WebDetails/4549" rel="noreferrer noopener" target="_blank" class="css-1p9dqzw"><img src="https://shopfront-cdn.tekoapis.com/common/da-dang-ky.png" alt="verified logo" class="css-t5rvn4"></a><div class="css-nyd45u"><a href="//www.dmca.com/Protection/Status.aspx?ID=73ee7811-7aa7-44d0-bb06-6c0df0da41d8&amp;refurl=https://phongvu.vn" title="DMCA.com Protection Status" class="dmca-badge"><img src="https://images.dmca.com/Badges/dmca-badge-w150-2x1-02.png?ID=73ee7811-7aa7-44d0-bb06-6c0df0da41d8" alt="DMCA.com Protection Status"></a></div></div><div class="css-16vu25q"></div></div></div></nav>
         </div>
    </div>
</div>